/**
 * Live-map read-model (spec-live-map.md story 1, Фаза A).
 *
 * Reads <local_path>/.flowmap/ artifacts generated by architect-portfolio's
 * scripts/flowmap/* (architecture.json, ui-flow.json, flowmap.mmd). keystack NEVER generates or
 * writes these files — same "source of truth is the project" invariant as the specs/ read-model
 * (src/db/index.ts upsertSpec). Used by the GET /map/:slug dashboard route; keystack-scan.sh has
 * its own bash+jq equivalent for the has_flowmap/map_crit/map_warn card-badge fields (same mapping
 * rule, documented in both places — see .ai-codex/lib.md).
 */
import { existsSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

export const FLOWMAP_STALE_DAYS = 7;

/**
 * architecture.json -> "kind" mapping to Mermaid classDef names, tuned to the kinds actually
 * emitted by architect-portfolio's architecture scanner across all 8 Track A projects (checked
 * 2026-07-12): client, frontend, backend, database, external-api, auth, queue, cache. Anything else
 * (future kind the generator adds) falls back to the neutral "node" class instead of breaking.
 */
const KIND_CLASS: Record<string, string> = {
  client: "client",
  frontend: "frontend",
  backend: "backend",
  database: "db",
  "external-api": "external",
  auth: "auth",
  queue: "queue",
  cache: "cache",
};
const DEFAULT_CLASS = "node";

/** Dark-theme palette, same spirit as the legacy flowmap.mmd `problem`/`terminal` classDefs. */
const CLASS_DEFS: Record<string, string> = {
  client: "classDef client fill:#1e293b,stroke:#64748b,color:#cbd5e1",
  frontend: "classDef frontend fill:#1e3a5f,stroke:#3b82f6,color:#bfdbfe",
  backend: "classDef backend fill:#164e63,stroke:#06b6d4,color:#a5f3fc",
  db: "classDef db fill:#14532d,stroke:#22c55e,color:#bbf7d0",
  external: "classDef external fill:#78350f,stroke:#f59e0b,color:#fde68a",
  auth: "classDef auth fill:#581c87,stroke:#a855f7,color:#e9d5ff",
  queue: "classDef queue fill:#4c1d95,stroke:#8b5cf6,color:#ddd6fe",
  cache: "classDef cache fill:#831843,stroke:#ec4899,color:#fbcfe8",
  node: "classDef node fill:#27272a,stroke:#71717a,color:#d4d4d8",
};

/** Escapes Mermaid-significant characters (quotes break the `["..."]` label, brackets/parens can
 * confuse the flowchart parser even inside quotes) so any label text is safe to inline. */
function escapeMermaidLabel(label: unknown): string {
  return String(label ?? "")
    .replace(/"/g, "#quot;")
    .replace(/\(/g, "#40;")
    .replace(/\)/g, "#41;")
    .replace(/\[/g, "#91;")
    .replace(/\]/g, "#93;");
}

/**
 * Pure converter: architecture.json (parsed) -> Mermaid flowchart text. Used as a fallback when a
 * project has no flowmap.mmd (mermaid.ts was cut from architect-portfolio's generator when it
 * pivoted to Excalidraw — spec-live-map.md story 2 finding) but does have an architecture graph.
 * Returns "" for missing/empty node data — callers must treat that as "nothing to render", not fall
 * back to a blank diagram.
 */
interface MermaidNode {
  id: string;
  kind: string;
  label: string;
}

export function architectureToMermaid(arch: any): string {
  const rawNodes = Array.isArray(arch?.nodes) ? arch.nodes : [];
  const nodes: MermaidNode[] = rawNodes
    .filter((n: any) => n && typeof n.id === "string" && n.id.length > 0)
    .map((n: any): MermaidNode => ({
      id: n.id as string,
      kind: typeof n.kind === "string" ? n.kind : "",
      label: typeof n.label === "string" && n.label.length > 0 ? n.label : n.id,
    }))
    .sort((a: MermaidNode, b: MermaidNode) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));
  if (nodes.length === 0) return "";

  const nodeIds = new Set(nodes.map((n: MermaidNode) => n.id));
  const rawEdges = Array.isArray(arch?.edges) ? arch.edges : [];
  const edges = rawEdges
    .filter((e: any) => e && nodeIds.has(e.from) && nodeIds.has(e.to))
    .map((e: any) => ({
      from: e.from as string,
      to: e.to as string,
      label: typeof e.label === "string" && e.label.length > 0 ? e.label : undefined,
    }))
    .sort((a: { from: string; to: string; label?: string }, b: { from: string; to: string; label?: string }) => {
      if (a.from !== b.from) return a.from < b.from ? -1 : 1;
      if (a.to !== b.to) return a.to < b.to ? -1 : 1;
      return (a.label ?? "").localeCompare(b.label ?? "");
    });

  const classOf = (kind: string) => KIND_CLASS[kind] ?? DEFAULT_CLASS;
  const usedClasses = new Set(nodes.map((n: MermaidNode) => classOf(n.kind)));
  const classDefOrder = Object.keys(CLASS_DEFS).filter((k) => usedClasses.has(k));

  const lines: string[] = ["flowchart TD"];
  for (const cls of classDefOrder) lines.push(`    ${CLASS_DEFS[cls]}`);
  for (const n of nodes) lines.push(`    ${n.id}["${escapeMermaidLabel(n.label)}"]`);
  for (const e of edges) {
    lines.push(
      e.label
        ? `    ${e.from} -->|"${escapeMermaidLabel(e.label)}"| ${e.to}`
        : `    ${e.from} --> ${e.to}`,
    );
  }

  const byClass = new Map<string, string[]>();
  for (const n of nodes) {
    const cls = classOf(n.kind);
    if (!byClass.has(cls)) byClass.set(cls, []);
    byClass.get(cls)!.push(n.id);
  }
  for (const cls of classDefOrder) {
    const ids = byClass.get(cls);
    if (ids && ids.length) lines.push(`    class ${ids.join(",")} ${cls}`);
  }

  return lines.join("\n") + "\n";
}

export interface FlowmapIssue {
  severity: "crit" | "warn";
  kind: string;
  message: string;
  screenId?: string;
}

export interface FlowmapSummary {
  /** `.flowmap/` directory exists at all — false means "not generated yet, run /sync". */
  exists: boolean;
  /** Raw flowmap.mmd content, or null when missing/unreadable/empty (see mmdError). */
  mmd: string | null;
  /** Set whenever mmd is null but `.flowmap/` exists — why there's nothing to render. */
  mmdError?: string;
  /** ui-flow.json .verdict.crit, 0 when ui-flow.json is absent (no data, not "zero issues"). */
  crit: number;
  /** ui-flow.json .verdict.warn + architecture.json .issues.length (mapping note below). */
  warn: number;
  /** ui-flow.json .issues[], already severity-tagged by the generator. */
  issues: FlowmapIssue[];
  /** architecture.json .issues[].message — no severity field in that contract, folded into warn. */
  archIssues: string[];
  archStats?: { nodes: number; edges: number };
  uiStats?: { screens: number; elements: number; edges: number };
  /** ISO mtime of the newest artifact file, for the "stale" badge. Null when nothing readable. */
  generatedAt: string | null;
  /** Whole days since generatedAt. Null when generatedAt is unknown. */
  staleDays: number | null;
}

function safeReadJson(path: string): any | null {
  try {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, "utf8"));
  } catch {
    return null;
  }
}

function fileMtimeIso(path: string): string | null {
  try {
    return statSync(path).mtime.toISOString();
  } catch {
    return null;
  }
}

const EMPTY: FlowmapSummary = {
  exists: false, mmd: null, crit: 0, warn: 0, issues: [], archIssues: [],
  generatedAt: null, staleDays: null,
};

/** Pure read of a project's `.flowmap/` artifacts. Never throws — missing/broken data degrades to EMPTY-shaped fields, not an exception (dashboard route must not 500 on a bad flowmap). */
export function readFlowmap(localPath: string): FlowmapSummary {
  if (!localPath) return { ...EMPTY };
  const dir = join(localPath, ".flowmap");
  if (!existsSync(dir)) return { ...EMPTY };

  const mmdPath = join(dir, "flowmap.mmd");
  let mmd: string | null = null;
  let mmdError: string | undefined;
  if (!existsSync(mmdPath)) {
    mmdError = "flowmap.mmd не найден в .flowmap/";
  } else {
    try {
      const raw = readFileSync(mmdPath, "utf8");
      if (raw.trim().length === 0) mmdError = "flowmap.mmd пуст";
      else mmd = raw;
    } catch (err) {
      mmdError = `flowmap.mmd не читается: ${(err as Error).message}`;
    }
  }

  const uiFlow = safeReadJson(join(dir, "ui-flow.json"));
  const architecture = safeReadJson(join(dir, "architecture.json"));

  // Fallback (spec-live-map.md story 2 finding): flowmap.mmd is legacy-only (3/8 Track A projects
  // still have one from before the Excalidraw pivot cut mermaid.ts from the generator) — a real,
  // richer mmd always wins when present; only synthesize from architecture.json when there's
  // nothing else to render.
  if (mmd === null && architecture) {
    const generated = architectureToMermaid(architecture);
    if (generated) {
      mmd = generated;
      mmdError = undefined;
    }
  }

  const uiCrit = Number(uiFlow?.verdict?.crit ?? 0) || 0;
  const uiWarn = Number(uiFlow?.verdict?.warn ?? 0) || 0;
  const archIssues: string[] = Array.isArray(architecture?.issues)
    ? architecture.issues.map((i: any) => String(i?.message ?? "")).filter(Boolean)
    : [];

  const issues: FlowmapIssue[] = Array.isArray(uiFlow?.issues)
    ? uiFlow.issues.map((i: any) => ({
        severity: i?.severity === "crit" ? "crit" as const : "warn" as const,
        kind: String(i?.kind ?? ""),
        message: String(i?.message ?? ""),
        screenId: i?.screenId ? String(i.screenId) : undefined,
      }))
    : [];

  const archStats = typeof architecture?.stats?.nodes === "number"
    ? { nodes: architecture.stats.nodes, edges: architecture.stats.edges ?? 0 }
    : undefined;
  const uiStats = typeof uiFlow?.stats?.screens === "number"
    ? { screens: uiFlow.stats.screens, elements: uiFlow.stats.elements ?? 0, edges: uiFlow.stats.edges ?? 0 }
    : undefined;

  const mtimes = [mmdPath, join(dir, "architecture.json"), join(dir, "ui-flow.json")]
    .map(fileMtimeIso)
    .filter((x): x is string => !!x)
    .sort();
  const generatedAt = mtimes.length ? mtimes[mtimes.length - 1]! : null;
  const staleDays = generatedAt ? Math.floor((Date.now() - new Date(generatedAt).getTime()) / 86400000) : null;

  return {
    exists: true,
    mmd,
    mmdError,
    crit: uiCrit,
    warn: uiWarn + archIssues.length,
    issues,
    archIssues,
    archStats,
    uiStats,
    generatedAt,
    staleDays,
  };
}
