#!/usr/bin/env bash
# keystack-export-table.sh — generates the "🗂️ Проекты" markdown table in ~/.claude/CLAUDE.md
# FROM the keystack DB (FORGE wave1 §6, story 5 of .ai-codex/specs/spec-forge-wave1.md in the
# keystack repo). NO LLM, deterministic bash+sqlite3+perl, same style/conventions as the sibling
# keystack-scan.sh / keystack-sync-skills.sh scripts.
#
# Usage:
#   keystack-export-table.sh              generate + splice into CLAUDE.md between the markers
#   keystack-export-table.sh --dry-run    print the generated table to stdout only, touch nothing
#
# Markers:
#   <!-- keystack:begin -->
#   <!-- keystack:end -->
# Only the content strictly between these two lines is ever replaced — everything else in
# CLAUDE.md (the "## 🗂️ Проекты" heading above and the canonical-slug sentence below) is left
# untouched by design; it lives OUTSIDE the marker block.
#
# Edge case (spec §6 / edge cases list): if CLAUDE.md doesn't exist, or either marker is missing,
# CLAUDE.md is NOT touched at all — the table is written to a fallback file instead, plus a
# warning on stderr. This is the one and only way this script ever avoids clobbering manual edits.
#
# Columns (Slug | Папка | Суть | Стек) map onto the DB as:
#   Slug  = projects.slug
#   Папка = basename(projects.local_path)   — VPS paths / secondary monorepo folders etc. are a
#           deliberate loss at this column's grain; anything worth keeping lives in `description`
#           instead (decided per-project during the first enrichment pass, see spec-forge-wave1.md
#           story 5 notes — e.g. botseller's VPS path, brieftube's second frontend folder).
#   Суть  = projects.description
#   Стек  = projects.frameworks + projects.language + projects.database, deduped & compacted.
#           Deliberately does NOT include projects.services (hosting/3rd-party providers such as
#           Vercel/Stripe/CF Pages/Twilio) — that is a different DB column with different
#           semantics and out of scope for this column per the spec.
#
# Env:
#   KEYSTACK_HOME       — DB directory (default ~/.keystack), same var the Node MCP server uses.
#   CLAUDE_MD           — target file to splice into (default ~/.claude/CLAUDE.md). Test-only seam.
#   GENERATED_FALLBACK  — file written when markers are missing (default
#                         ~/.claude/projects-table.generated.md). Test-only seam.
#
# Exit code: 0 on success, including the "markers missing" edge case (that's a handled outcome,
# not a failure). Non-zero only when the DB itself is unusable.

set -o pipefail   # deliberately NOT -e/-u — see keystack-scan.sh for the bash 3.2 rationale

KEYSTACK_HOME="${KEYSTACK_HOME:-$HOME/.keystack}"
DB="$KEYSTACK_HOME/keystack.db"
CLAUDE_MD="${CLAUDE_MD:-$HOME/.claude/CLAUDE.md}"
GENERATED_FALLBACK="${GENERATED_FALLBACK:-$HOME/.claude/projects-table.generated.md}"
BEGIN_MARKER="<!-- keystack:begin -->"
END_MARKER="<!-- keystack:end -->"

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
  esac
done

if [ ! -f "$DB" ]; then
  echo "keystack-export-table.sh: no DB at $DB — run the keystack MCP server once first (it creates/migrates it)" >&2
  exit 1
fi

sql() { sqlite3 -separator '|' "$DB" "$@"; }

# Compact "Стек" cell: JSON array `frameworks` + `/`-separated `language` + `database`, deduped
# (case-insensitively) and comma-joined, order preserved. See the header comment above for why
# `services` is intentionally excluded.
compact_stack() {
  local frameworks_json="$1" language="$2" database="$3"
  perl -e '
    use strict; use warnings;
    my ($fw_json, $lang, $db) = @ARGV;
    my @parts;
    while ($fw_json =~ /"([^"]+)"/g) { push @parts, $1; }
    push @parts, split(m{\s*/\s*}, $lang) if defined $lang && length $lang;
    push @parts, $db if defined $db && length $db;
    my %seen;
    my @out = grep { !$seen{lc $_}++ } grep { length } @parts;
    print join(", ", @out);
  ' "$frameworks_json" "$language" "$database"
}

# Escapes a value for safe placement inside a markdown table cell: a stray `|` would otherwise
# break the row into extra columns.
md_escape() {
  printf '%s' "$1" | sed 's/|/\\|/g'
}

generate_table() {
  local rows slug local_path description language frameworks database folder stack
  echo "<!-- generated by keystack-export-table.sh — ручные правки таблицы будут перезаписаны, правь БД (keystack) -->"
  echo "| Slug | Папка | Суть | Стек |"
  echo "|------|-------|------|------|"
  rows=$(sql "SELECT slug, local_path, description, language, frameworks, database FROM projects ORDER BY slug;")
  while IFS='|' read -r slug local_path description language frameworks database; do
    [ -z "$slug" ] && continue
    folder=""
    [ -n "$local_path" ] && folder=$(basename "$local_path")
    stack=$(compact_stack "$frameworks" "$language" "$database")
    printf '| `%s` | `%s` | %s | %s |\n' \
      "$(md_escape "$slug")" "$(md_escape "$folder")" "$(md_escape "$description")" "$(md_escape "$stack")"
  done <<< "$rows"
}

TABLE=$(generate_table)

if [ "$DRY_RUN" -eq 1 ]; then
  printf '%s\n' "$TABLE"
  exit 0
fi

if [ ! -f "$CLAUDE_MD" ] || ! grep -qF "$BEGIN_MARKER" "$CLAUDE_MD" || ! grep -qF "$END_MARKER" "$CLAUDE_MD"; then
  printf '%s\n' "$TABLE" > "$GENERATED_FALLBACK"
  echo "keystack-export-table.sh: WARNING — markers ($BEGIN_MARKER / $END_MARKER) not found in $CLAUDE_MD; wrote generated table to $GENERATED_FALLBACK instead. CLAUDE.md left untouched." >&2
  exit 0
fi

# Splice: replace only the text strictly between BEGIN_MARKER's line and END_MARKER's line.
# Perl with -0777 (slurp whole file) + /s (dot matches newline) does a single, non-greedy,
# marker-scoped substitution — robust to UTF-8 content and to however many blank lines currently
# sit between the markers, unlike a line-oriented sed/awk rewrite.
EXPORT_TABLE_CONTENT="$TABLE" BEGIN_MARKER="$BEGIN_MARKER" END_MARKER="$END_MARKER" perl -i -0777pe '
  my $begin = quotemeta($ENV{BEGIN_MARKER});
  my $end   = quotemeta($ENV{END_MARKER});
  my $table = $ENV{EXPORT_TABLE_CONTENT};
  s/($begin\n).*?(\n$end)/$1 . $table . $2/se;
' "$CLAUDE_MD"

echo "keystack-export-table.sh: wrote $(sql "SELECT COUNT(*) FROM projects;") project row(s) into $CLAUDE_MD"
